.Dd $Mdocdate$
.Dt TILDE.INSTITUTE 7
.Os
.Sh TILDE.INSTITUTE
.Nm tilde.institute
.Nd a public unix system
.Sh SYNOPSIS
ssh username@tilde.institute
.Sh DESCRIPTION

Welcome to tilde.institute! This is an OpenBSD machine whose purpose is 
to provide a space in the tildeverse for experimentation with and 
education of the OpenBSD operating system. A variety of editors, shells, 
and compilers are installed to allow for development in a native OpenBSD 
environment. OpenBSD's httpd(8) is configured with slowcgi(8) as the 
fastcgi provider and sqlite3 is available.

.Sh NOTABLE SOFTWARE
.Ss Compilers

The following compilers and interpreters are provided:
.Bd -offset indent
.Bl -compact
.It
brainf*ck 2.7.1
.It
clang 8.0.1
.It
clisp 2.49
.It
clojure 1.10.0.4
.It
elixir 1.9.1
.It
erlang 21.2
.It
gcc 8.3.0 (includes Objective-C support)
.It
gforth 0.7.3
.It
ghc 8.6.4
.It
gnat 8.3.0
.It
go 1.13.1
.It
guile 1.8.8
.It
jdk 11.0.5.8.1 (environment setup required)
.It
lua 5.3.5 and 5.1.5
.It
mono 5.20.1.34
.It
nasm 2.14.02
.It
nim 1.0.4
.It
node.js 10.16.3
.It
perl 5.28.2
.It
php 7.3.16
.It
python (2.7.16 & 3.7.4)
.It
racket 7.4
.It
rakudo 2018.12
.It
ruby 2.5.5 (and 2.6.6)
.It
rust 1.38
.It
scala 2.12.3
.It
yasm 1.3.0
.El
.Ed

.Ss Shells
            
Your interactive shell can be changed with the chsh command. The shells available:
.Bd -offset indent
.Bl -compact
.It
/bin/ksh (default)
.It
/bin/sh
.It
/bin/csh
.It
/usr/local/bin/bash
.It
/usr/local/bin/dash
.It
/usr/local/bin/zsh
.It
/usr/local/bin/fish
.It
/usr/local/bin/tcsh
.It
/usr/local/bin/elvish
.El
.Ed

.Ss IRC
            
The IRC clients available by default are:
.Bd -offset indent
.Bl -compact
.It
weechat
.It
irssi
.It
ircII
.El
.Ed

.Sh BUGS
Contact the admins <admins@tilde.institute> or stop by #institute on irc.
.Sh NOTES
Mailing lists are now available for tilde.institute. Web archive and information available at
.Ur
https://lists.tildeverse.org/postorius/lists/institute.lists.tildeverse.org/
.Ue 
.Sh SEE ALSO
httpd(8), slowcgi(8), ksh(1), bash(1), chsh(1)
.Sh AUTHORS
.An Knight <knight@tilde.institute>
